export const microbrute = {
  id: 'microbrute',
  name: 'MicroBrute',
  description: 'Raw analog monosynth with a Steiner-Parker filter and unison saw stack. Built for bass lines, leads, and harmonic mayhem.',
  panel: '/microbrute-panel.png',

  modMatrixColumns: [
    { label: 'CV OUT', keys: ['mod_env_out', 'mod_lfo_out'] },
    { label: '', keys: ['mod_metal_in', 'mod_pitch_in'] },
    { label: '', keys: ['mod_saw_in', 'mod_filter_in'] },
    { label: 'CV IN', keys: ['mod_sub_in', 'mod_pwm_in'] },
  ],

  params: {

    // ─── OSCILLATOR ───────────────────────────────────────
    osc_saw: {
      label: 'Sawtooth',
      group: 'Oscillator',
      type: 'knob',
      default: 1,
      min: 0,
      max: 1,
      x: 36.3,
      y: 22,
      description: 'Sawtooth wave level. The brightest and richest wave, good for leads and basses.',
    },
    osc_ultrasaw: {
      label: 'Ultrasaw',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 36.4,
      y: 11,
      description: 'Adds phase-shifted saw layers on top of the main saw, simulating a detuned unison. Higher = thicker and fatter.',
    },
    osc_square: {
      label: 'Square',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 43.8,
      y: 22,
      description: 'Square wave level. Hollow and beefy, classic for chords and vintage leads.',
    },
    osc_pulse_width: {
      label: 'Pulse Width',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 43.8,
      y: 11,
      description: 'Width of the square wave. Center (0.5) is a pure square, extremes give thin or nasal pulse tones.',
    },
    osc_triangle: {
      label: 'Triangle',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 51.2,
      y: 22,
      description: 'Triangle wave level. Soft and flute-like, lowest harmonic content of the three waves.',
    },
    osc_metalizer: {
      label: 'Metalizer',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 51.1,
      y: 11,
      description: 'Folds the triangle wave into metallic, harsh harmonics. Higher = more aggressive and distorted.',
    },
    osc_overtone: {
      label: 'Overtone',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 29,
      y: 22,
      description: 'Sub-oscillator level. Adds low-end weight or a 5th interval harmonic depending on the Overtone Mode switch.',
    },
    osc_overtone_switch: {
      label: 'Sub > Fifth',
      group: 'Oscillator',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 29.1,
      y: 11,
      description: 'Sub-oscillator pitch mode. 0 = off, 0.5 = sub octave, 1 = fifth above.',
    },

    // ─── FILTER ───────────────────────────────────────────
    filter_mode: {
      label: 'Filter Mode',
      group: 'Filter',
      type: 'switch',
      options: ['lowpass', 'bandpass', 'highpass'],
      default: 'lowpass',
      x: 58.2,
      y: 25.1,
      description: 'Steiner-Parker filter mode. Lowpass = removes highs (warm), Bandpass = removes lows and highs (nasal), Highpass = removes lows (bright).',
    },
    filter_cutoff: {
      label: 'Cutoff',
      group: 'Filter',
      type: 'knob',
      default: 0.5,
      min: 0,
      max: 1,
      x: 58.5,
      y: 11,
      description: 'Filter cutoff frequency. Lower = darker and muffled, higher = brighter and open. The most important tone-shaping knob.',
    },
    filter_resonance: {
      label: 'Resonance',
      group: 'Filter',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 66,
      y: 11,
      description: 'Emphasis at the cutoff frequency. Higher = more resonant and whistling. Above ~0.9 the filter self-oscillates.',
    },
    filter_env_amt: {
      label: 'Env Amount',
      group: 'Filter',
      type: 'knob',
      default: 0.5,
      min: 0,
      max: 1,
      x: 65.8,
      y: 22,
      description: 'How much the ADSR envelope opens the filter over time. Higher = more dramatic filter sweep on each note.',
    },
    filter_kbd_tracking: {
      label: 'KBD Tracking',
      group: 'Filter',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 73.2,
      y: 22,
      description: 'How much keyboard pitch raises the filter cutoff. Higher = filter opens more on high notes, keeping tone consistent across the keyboard.',
    },
    brute_factor: {
      label: 'Brute Factor',
      group: 'Filter',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 73.4,
      y: 11,
      description: 'Internal feedback distortion. Low = warm saturation. Above ~0.65 produces wild, unstable feedback.',
    },

    // ─── ENVELOPE ─────────────────────────────────────────
    env_attack: {
      label: 'Attack',
      group: 'Envelope',
      type: 'slider',
      default: 0,
      min: 0,
      max: 1,
      x: 58.3,
      y: 43,
      description: 'Time to reach full volume after a key press. Low = snappy, high = slow fade-in like a pad.',
    },
    env_decay: {
      label: 'Decay',
      group: 'Envelope',
      type: 'slider',
      default: 0,
      min: 0,
      max: 1,
      x: 63.1,
      y: 43,
      description: 'Time to fall from peak to sustain level after the attack. Low = punchy, high = long fall.',
    },
    env_sustain: {
      label: 'Sustain',
      group: 'Envelope',
      type: 'slider',
      default: 0,
      min: 0,
      max: 1,
      x: 68,
      y: 43,
      description: 'Volume level held while the key is pressed. 0 = percussive with no sustain, 1 = full sustained note.',
    },
    env_release: {
      label: 'Release',
      group: 'Envelope',
      type: 'slider',
      default: 0,
      min: 0,
      max: 1,
      x: 72.8,
      y: 43,
      description: 'Time for the sound to fade out after key release. Low = abrupt stop, high = long tail.',
    },
    env_vca_switch: {
      label: 'VCA',
      group: 'Envelope',
      type: 'switch',
      options: ['env', 'gate'],
      default: 'env',
      x: 51.1,
      y: 48.6,
      description: 'Volume control mode. Env = shaped by the ADSR envelope (normal). Gate = full volume for the entire key press, like an organ.',
    },

    env_amt: {
      label: 'Env Amount',
      group: 'Envelope',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 51.2,
      y: 37,
      description: 'Envelope modulation depth to the VCA.',
    },

    // ─── LFO ──────────────────────────────────────────────
    lfo_wave: {
      label: 'LFO Wave',
      group: 'LFO',
      type: 'switch',
      options: ['square', 'saw', 'sine'],
      default: 'sine',
      x: 36.6,
      y: 48.3,
      description: 'LFO waveform shape. Sine/triangle = smooth wobble, sawtooth = ramp motion, square = abrupt switching, random = sample-and-hold steps.',
    },
    lfo_rate: {
      label: 'LFO Rate',
      group: 'LFO',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 43.7,
      y: 37,
      description: 'LFO speed. Low = slow sweep or tremolo, high = fast modulation approaching audio-rate FM effects.',
    },
    lfo_amount: {
      label: 'LFO Amount',
      group: 'LFO',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 36.3,
      y: 37,
      description: 'LFO modulation depth. 0 = no effect, 1 = full modulation range applied to the destination.',
    },
    lfo_sync: {
      label: 'LFO Sync',
      group: 'LFO',
      type: 'switch',
      options: ['free', 'arp'],
      default: 'free',
      x: 43.8,
      y: 48.4,
      description: 'LFO clock source. Free = runs at its own rate, Arp = syncs to the sequencer or arpeggiator tempo.',
    },

    // ─── MOD WHEEL ────────────────────────────────────────
    mod_wheel_dest: {
      label: 'Mod Wheel Dest',
      group: 'Mod Wheel',
      type: 'switch',
      options: ['lfo', 'cutoff'],
      default: 'lfo',
      x: 29.3,
      y: 48.1,
      description: 'Mod wheel modulation destination. Cutoff = sweeps the filter, LFO = increases vibrato/tremolo intensity.',
    },

    // ─── GLOBAL ───────────────────────────────────────────
    glide: {
      label: 'Glide',
      group: 'Global',
      type: 'knob',
      default: 0,
      min: 0,
      max: 1,
      x: 29,
      y: 37,
      description: 'Portamento time between notes. 0 = instant pitch change, higher = slow slide between notes.',
    },

    // ─── MOD MATRIX ───────────────────────────────────────
    mod_env_out: {
      label: 'Env Out',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'out',
      default: null,
      x: 79.7,
      y: 10,
      description: 'Envelope CV output. Drag to a destination jack to patch modulation.',
    },
    mod_lfo_out: {
      label: 'LFO Out',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'out',
      default: null,
      x: 79.8,
      y: 14.8,
      description: 'LFO CV output. Drag to a destination jack to patch modulation.',
    },
    mod_metal_in: {
      label: 'Metal',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'in',
      default: null,
      x: 83.1,
      y: 9.9,
      description: 'Metalizer modulation input.',
    },
    mod_pitch_in: {
      label: 'Pitch',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'in',
      default: null,
      x: 83.1,
      y: 14.8,
      description: 'Oscillator pitch modulation input.',
    },
    mod_saw_in: {
      label: 'Saw',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'in',
      default: null,
      x: 86.4,
      y: 9.9,
      description: 'Ultrasaw modulation input.',
    },
    mod_filter_in: {
      label: 'Filter',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'in',
      default: null,
      x: 86.5,
      y: 14.8,
      description: 'Filter cutoff modulation input.',
    },
    mod_sub_in: {
      label: 'Sub',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'in',
      default: null,
      x: 89.7,
      y: 10,
      description: 'Sub oscillator / Overtone modulation input.',
    },
    mod_pwm_in: {
      label: 'PWM',
      group: 'Mod Matrix',
      type: 'jack',
      direction: 'in',
      default: null,
      x: 89.8,
      y: 14.8,
      description: 'Pulse width modulation input.',
    },
  },
}
